version: "2"

volumes:
  grafana-storage:
  promtail-logs:
  influxdb:
# victoria: 

networks:
  loki:

services:
  loki:
    image: grafana/loki:1.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - promtail-logs:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

#  victoria:
#    image: victoriametrics/victoria-metrics
#    volumes:
#      - victoria:/victoria-metrics-data
#    ports:
#      - '8428:8428'
#    networks:
#      - loki
#    mem_limit: 4096m

  influxdb:
    image: influxdb:latest
    networks:
      - loki
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DATA_INDEX_VERSION=tsi1

  grafana:
    image: grafana/grafana:master
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki
